apiVersion: apps/v1
kind: Deployment
metadata:
  name: sava-stock
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
  template:
    spec:
      containers:
      - name: sava-stock
        image: vampio/sava-analytics:latest
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        envFrom:
        - configMapRef:
            name: sava-stock-configmap