apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

## specify here the resource you want to include
resources:
- deployment.yaml

## labels to add to all resources
commonLabels:
  app: sava-product

## image tag
images:
- name: /jasongriffin/sava-product
  newTag: 1.0.13
- name: vampio/sava-product
  newTag: latest
nameSuffix: -v1.0.13
