apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

## specify here the resource you want to include
resources:
- deployment.yaml

## appended to the names of all resources
nameSuffix: -2.0.8

## labels to add to all resources
commonLabels:
  app: sava-cart
  version: 2.0.8

## image tag
images:
- name: vampio/sava-cart
  newTag: 2.0.8

configMapGenerator:
- name: sava-cart-configmap
  behavior: create
  env: sava-cart-configMap.env
- name: sava-order-configmap
  behavior: create
  env: sava-order-configMap.env