apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

## specify here the resource you want to include
resources:
- deployment.yaml

## appended to the names of all resources
nameSuffix: -0.1.0

## labels to add to all resources
commonLabels:
  app: sava-ratings
  version: 0.1.0

## image tag
images:
- name: vampio/sava-ratings
  newTag: 0.1.0
  
secretGenerator:
- name: sava-ratings-data
  behavior: create
  files:
  - db.json