apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

## specify here the resource you want to include
resources:
- deployment.yaml

## labels to add to all resources
commonLabels:
  app: sava-cart

## image tag
images:
- name: jasongriffin/sava-cart
  newTag: 2.1.4
- name: vampio/sava-cart
  newTag: latest
  
configMapGenerator:
- behavior: create
  env: configMap.env
  name: sava-cart-configmap
nameSuffix: -v2.1.4
