apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

## specify here the resource you want to include
resources:
- deployment.yaml

## appended to the names of all resources
nameSuffix: -2.0.1

## labels to add to all resources
commonLabels:
  app: sava-product
  version: 2.0.1

## image tag
images:
- name: vampio/sava-product
  newTag: 2.0.1

secretGenerator:
- name: sava-product-data
  behavior: create
  files:
  - db.json